return {
  ["workshop-1818688368"]={ configuration_options={  }, enabled=true },
  ["workshop-2078243581"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="SP", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-358749986"]={
    configuration_options={ IndicatorSize=3, MaxIndicator=7000, PlayerIndicators=1 },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      STACK_SIZE_LARGEITEM=10,
      STACK_SIZE_MEDITEM=20,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=40,
      STACK_SIZE_TINYITEM=60 
    },
    enabled=true 
  },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default" 
    },
    enabled=true 
  },
  ["workshop-623749604"]={
    configuration_options={
      Craft="Normal",
      Destroyable="DestroyByAll",
      FoodSpoilage=1,
      Language="Sp",
      Position="Center",
      Slots=80 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-885290954"]={
    configuration_options={},
    enabled=true 
  },
  -- Agregar nuevos mods aquí:
  -- ["workshop-ID_DEL_MOD"]={ configuration_options={}, enabled=true }, 
}