version: '3.8'

services:
  dst-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dont-starve-together
    restart: unless-stopped
    ports:
      - "10999:10999/udp"  # Master server port
      - "10998:10998/udp"  # Caves server port
      - "10888:10888/tcp"  # Cluster communication
      - "27017:27017/tcp"  # Caves server port for Steam
      - "27018:27018/tcp"  # Master server port for Steam
      - "8767:8767/tcp"    # Caves authentication port
      - "8768:8768/tcp"    # Master authentication port
    volumes:
      - ./data:/home/steam/.klei/DoNotStarveTogether/DoNotStarveTogether
      - ./game:/home/steam/dst
    environment:
      - CLUSTER_NAME=dts-server
      - CLUSTER_PASSWORD=
      - MAX_PLAYERS=12
      - GAME_MODE=survival
      - PVP=false
      - PAUSE_WHEN_EMPTY=true
    networks:
      - dst-network

networks:
  dst-network:
    driver: bridge